name: Conventional Commit Check

on:
  pull_request:
    branches: [main]

jobs:
  check-commits:
    runs-on: ubuntu-latest
    environment: EMAIL_USER
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check for Conventional Commits
        uses: wagoid/commitlint-github-action@v2
        with:
          configFile: "./commitlint.config.js"

      - name: Close PR if Commit Check Fails
        if: failure() # This step will execute only if the commitlint check fails
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This PR has been closed because it does not follow Conventional Commits.'
            })
            github.pulls.update({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            })

      - name: Send failure notification
        if: failure() # Ensures that this step only runs if the commitlint check fails
        run: |
          npm install
          node ./scripts/sendEmail.js
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
