name: Night Build

on:
  schedule:
    - cron: "30 19 * * *" # At 19:30 UTC every day
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: EMAIL_USER
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to DockerHub (if necessary)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Start services
        run: docker-compose up -d

      - name: Install Dependencies
        run: docker-compose run --rm web pip install -r requirements.txt

      - name: Install Test Dependencies
        run: docker-compose run --rm web pip install pytest pytest-asyncio

      - name: Run Tests
        run: docker-compose run --rm web pytest

      - name: Build Docker Image
        if: success()
        run: docker build -t willaoao/devops:${{ github.sha }} .

      - name: Log in to DockerHub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: willaoao/devops:${{ github.sha }}

      - name: Send failure notification
        if: failure()
        run: node ./scripts/sendEmail.js
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Clean up
        if: always()
        run: docker-compose down
